datasets:
  msrvtt_cap:
    data_type: videos
    build_info:
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/cap_train.json
          storage: msrvtt/annotation/cap_train.json
        val:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/cap_val.json
          storage: msrvtt/annotation/cap_val.json
        test:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/cap_test.json
          storage: msrvtt/annotation/cap_test.json
      videos:
        storage: msrvtt/frames

